version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: testdev-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      my-network:
        aliases:
          - db

networks:
  my-network:
    driver: bridge